apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anythingintopdfbot
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: anythingintopdfbot
    newName: ghcr.io/YOUR_ORG/anythingintopdfbot
    newTag: latest
